name: Workflow React

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Check no node_modules in root
      run: |
        if [ -d "./node_modules" ]; then
          echo "❌ Error: 'node_modules' directory found at the root level. Remove it before pushing.";
          exit 1;
        else
          echo "✅ No 'node_modules' directory found at the root level.";
        fi

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: npm

    - name: Install dependencies
      run: npm install
      working-directory: client

    - name: Build the application
      run: npm run build
      working-directory: client
